name: CI

on:
  push:
    branches: [ "main" ]    

jobs:
  
  build:
    env:
      platform: aws
      region: us-west-1
      account: 1111111
    runs-on: ubuntu-latest

    steps:
      - name: "Display Message"
        run: echo "Hola Daniel"

      - name: "mostrando variables de entorno"
        run: |
          echo "Esto es el valor de platform: ${{env.platform}}"
          echo "Esto es el valor de region: ${{env.region}}"
          echo "Esto es el valor de account: ${{env.account}}"