name: CI

on:
  push:
    branches: [ "main" ]    

jobs:
  
  build:
    env:
      platform: aws
      region: us-west-1
      account: 1111111
      MICLAVE: ${{secrets.MICLAVE}}
      MINOMBRE: ${{secrets.MINOMBRE}}
    runs-on: ubuntu-latest

    steps:
      - name: "Display Message"
        run: echo "Hola Daniel"

      - name: "mostrando variables de entorno"
        if: ${{ env.platform == 'azure' }}
        run: |
          echo "Esto es el valor de platform: ${{ env.platform }}"
          echo "Esto es el valor de region: ${{ env.region }}"
          echo "Esto es el valor de account: ${{ env.account }}"

      - name: "VARIABLES POR DEFECTO"
        run: |
          #echo "Evento: ${{ toJSON(github) }}"
          #echo "github.actor: ${{ toJSON(github.actor) }}"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY" 
          echo "MICLAVE: ${{ env.MICLAVE }}" 
          echo "MINOMBRE: ${{ env.MINOMBRE }}" 